name = "ssl-manager-web"
compatibility_date = "2024-01-01"

[build]
command = "pnpm build"

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
name = "ssl-manager-web-prod"

[env.staging]
name = "ssl-manager-web-staging"