name = "ssl-manager-web-main"
compatibility_date = "2024-01-01"

[build]
command = "pnpm build"

[[assets]]
bucket = "./dist"

[env.production]
name = "ssl-manager-web-main-prod"

[env.staging]
name = "ssl-manager-web-main-staging"